### ISSUE TITLE
Blank installation

### ISSUE THREAD

**Issue by TechBill** [suntorytimed/resourcespace-docker#4] opened 2022-07-18 21:21 UTC
When I execute your docker, it does load a resourcespace setup page to input the database and admin information but after I clicked install, it redirect me to a blank page.  

Any idea why it loads the setup page fine but installation is redirected to a blank page?

**Comment by nephews** [comment] 2022-09-07 11:55
I have exactly the same problem.

**Comment by suntorytimed** [comment] 2022-10-25 11:03
Using a minimal docker-compose.yml to deploy the container and a mariadb database I can finish the installation successfully. Have you entered the correct address to the mariadb database on the page? Though usually it should write an error in this case. This might also be a ResourceSpace issue unrelated to the container. If you have any kind of error or log that would be helpful. Same for the configuration you are using.

**Comment by suntorytimed** [comment] 2022-11-18 10:49
@TechBill @nephews are you sure that you have the proper access to the mounted /var/www/html/include? I could reproduce this in an environment in which the user inside the container doesn't have write/read access to the volume mounted in /var/www/html/include.

**Comment by suntorytimed** [comment] 2022-11-24 09:43
Closing due to missing feedback and the issue only being reproducible with an incorrect setup. Please ensure you have the correct permissions on the volumes mounted to /var/www/html/include and /var/www/html/filestore. In case this issue persists afterwards please reopen and provide logs.

**Closed as completed by suntorytimed** 2022-11-24 09:43 UTC
